name: test

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * *'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the package
        run: |
          yarn
          yarn build

      - name: Test the scraper
        run: yarn test

      - name: Create artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: scraps
          path: scraps/